USE [master]
GO

/****** Object:  Database [miVacationSurfer]    Script Date: 8/4/2014 3:08:15 PM ******/
DROP DATABASE [miVacationSurfer]
GO

/****** Object:  Database [miVacationSurfer]    Script Date: 8/4/2014 3:08:15 PM ******/
CREATE DATABASE [miVacationSurfer]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'miVacationSurfer', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\miVacationSurfer.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'miVacationSurfer_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\miVacationSurfer_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [miVacationSurfer] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [miVacationSurfer].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [miVacationSurfer] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [miVacationSurfer] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [miVacationSurfer] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [miVacationSurfer] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [miVacationSurfer] SET ARITHABORT OFF 
GO

ALTER DATABASE [miVacationSurfer] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [miVacationSurfer] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [miVacationSurfer] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [miVacationSurfer] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [miVacationSurfer] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [miVacationSurfer] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [miVacationSurfer] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [miVacationSurfer] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [miVacationSurfer] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [miVacationSurfer] SET  DISABLE_BROKER 
GO

ALTER DATABASE [miVacationSurfer] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [miVacationSurfer] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [miVacationSurfer] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [miVacationSurfer] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [miVacationSurfer] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [miVacationSurfer] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [miVacationSurfer] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [miVacationSurfer] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [miVacationSurfer] SET  MULTI_USER 
GO

ALTER DATABASE [miVacationSurfer] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [miVacationSurfer] SET DB_CHAINING OFF 
GO

ALTER DATABASE [miVacationSurfer] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [miVacationSurfer] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [miVacationSurfer] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [miVacationSurfer] SET  READ_WRITE 
GO

