//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace miVacationSurfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityType
    {
        public ActivityType()
        {
            this.ActivityTypeSeasons = new HashSet<ActivityTypeSeason>();
            this.LocationActivityTypes = new HashSet<LocationActivityType>();
        }
    
        public int Id { get; set; }
        public string ActivityTypeName { get; set; }
        public string ActivityTypeDesc { get; set; }
    
        public virtual ICollection<ActivityTypeSeason> ActivityTypeSeasons { get; set; }
        public virtual ICollection<LocationActivityType> LocationActivityTypes { get; set; }
    }
}
