//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace miVacationSurfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public Activity()
        {
            this.ActivityReviews = new HashSet<ActivityReview>();
            this.SeasonActivities = new HashSet<SeasonActivity>();
        }
    
        public int Id { get; set; }
        public string ActivityName { get; set; }
        public string ActivityDesc { get; set; }
    
        public virtual ICollection<ActivityReview> ActivityReviews { get; set; }
        public virtual ICollection<SeasonActivity> SeasonActivities { get; set; }
    }
}
