//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace miVacationSurfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityReview
    {
        public int Id { get; set; }
        public int ActivityRating { get; set; }
        public System.DateTime ActivityDate { get; set; }
        public string ActivityPro { get; set; }
        public string ActivityCon { get; set; }
        public string ActivityReviewDetails { get; set; }
        public int ActivityId { get; set; }
    
        public virtual Activity Activity { get; set; }
    }
}
