//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace miVacationSurfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationReview
    {
        public int Id { get; set; }
        public int LocationRating { get; set; }
        public System.DateTime LocationDate { get; set; }
        public string LocationPro { get; set; }
        public string LocationCon { get; set; }
        public string LocationReviewDetails { get; set; }
        public int LocationId { get; set; }
    
        public virtual Location Location { get; set; }
    }
}
