//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace miVacationSurfer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Location
    {
        public Location()
        {
            this.LocationActivityTypes = new HashSet<LocationActivityType>();
            this.LocationReviews = new HashSet<LocationReview>();
        }

        [Display(Name = "Location")]
        public int Id { get; set; }

        [Display(Name = "Location")]
        public string LocationName { get; set; }

        [Display(Name = "Description")]
        public string LocationDesc { get; set; }
        public string Size { get; set; }

        [Display(Name = "Region")]
        public int RegionId { get; set; }
    
        public virtual Region Region { get; set; }
        public virtual ICollection<LocationActivityType> LocationActivityTypes { get; set; }
        public virtual ICollection<LocationReview> LocationReviews { get; set; }
    }
}
