//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace miVacationSurfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationActivityType
    {
        public int Id { get; set; }
        public int ActivityTypeId { get; set; }
        public int LocationId { get; set; }
    
        public virtual ActivityType ActivityType { get; set; }
        public virtual Location Location { get; set; }
    }
}
