//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace miVacationSurfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Season
    {
        public Season()
        {
            this.ActivityTypeSeasons = new HashSet<ActivityTypeSeason>();
            this.SeasonActivities = new HashSet<SeasonActivity>();
        }
    
        public int Id { get; set; }
        public string SeasonName { get; set; }
    
        public virtual ICollection<ActivityTypeSeason> ActivityTypeSeasons { get; set; }
        public virtual ICollection<SeasonActivity> SeasonActivities { get; set; }
    }
}
